databases:
  mongodb:
    uri: your_mongodb_uri_here
    db_name: your_mongodb_db_name_here

mcp:
  coral_protocol:
    sse_url: http://coral-server:5555/devmode/exampleApplication/privkey/session1/sse
    timeout_ms: 30000

agents:
  llm_model:
    provider: azure_openai
    api_version: 2025-01-01-preview
    base_url: your-base_url
    api_key: ${MODEL_API_KEY}
    model_name: gpt-4o
    temperature: 0.1
    max_tokens: 16000
