databases:
  mongodb:
    uri: your_mongodb_uri_here
    db_name: your_mongodb_db_name_here

mcp:
  coral_protocol:
    sse_url: http://coral-server:5555/devmode/exampleApplication/privkey/session1/sse
    timeout_ms: 60000

agents:
  llm_model:
    provider: google_genai
    api_key: ${MODEL_API_KEY}
    model_name: gemini-1.5-pro
    temperature: 0.1
    max_tokens: 16000
