mongo:
  uri: "your-mongo-db-uri"
  db_name: "database"

strategy_agent:
  url: "your-strategy-agent-url"
  port: "your-strategy-agent-port"

vault_management:
  url: "your-vault-management-url"
  port: "your-vault-management-port"
