databases:
  mongodb:
    uri: "mongodb://131.153.202.197:27777/"
    db_name: "defi_agent_db"

mcp:
  coral_protocol:
    sse_url: http://localhost:5555/devmode/exampleApplication/privkey/session1/sse
    timeout_ms: 60000

agents:
  llm_model:
    provider: azure_openai
    api_version: 2025-01-01-preview
    base_url: https://openai-centic.openai.azure.com/openai/deployments/gpt-4o/chat/completions?api-version=2023-03-15-preview
    api_key: ${MODEL_API_KEY}
    model_name: gpt-4o
    temperature: 0.1
    max_tokens: 16000
