version: '3.8'

services:
  paper-vault:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paper-vault
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env